//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sell_Buy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Regions = new HashSet<Region>();
            this.Sites = new HashSet<Site>();
            this.Users = new HashSet<User>();
        }
    
        public int id { get; set; }
        public string name_country { get; set; }
    
        public virtual ICollection<Region> Regions { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
