//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sell_Buy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazine
    {
        public Magazine()
        {
            this.Products = new HashSet<Product>();
            this.Users = new HashSet<User>();
        }
    
        public int id { get; set; }
        public string name_magazine { get; set; }
        public string C_image { get; set; }
        public int C_status { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
